Description: Create NAT Gateway
Parameters:
  SSHKey:
    Description: Please enter key name.
    Type: String
    Default: MyAWSKey
  BaseStackName:
    Description: Please enter name of Base Stack
    Type: String
    Default: MyBase
  InstanceStackName:
    Description: Please enter name of Instance Stack
    Type: String
    Default: MyInstances

Resources:

  MyFirsPrivatetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: 
        Fn::ImportValue:
          !Sub "${BaseStackName}:VPC"
      Tags:
        - Key: Name
          Value: MyFirsPrivatetRouteTable

  MyFirstPrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyFirsPrivatetRouteTable
      SubnetId:
        Fn::ImportValue:
          !Sub "${BaseStackName}:MyFirstPrivateSubnet"

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      ConnectivityType: public
      SubnetId:
        Fn::ImportValue:
          !Sub "${BaseStackName}:MyFirstSubnet"
      AllocationId: !GetAtt MyEIP.AllocationId
      Tags:
      - Key: Name
        Value: NATgateway

  NATRoute:
   Type: AWS::EC2::Route
   Properties:
     RouteTableId: !Ref MyFirsPrivatetRouteTable
     DestinationCidrBlock: 0.0.0.0/0
     NatGatewayId: !Ref NATGateway
